version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=1
      - DB_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/rent_all
    ports:
      - "8080:8080"

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "rent_all"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    ports:
      - "5432:5432"
    volumes:
      - "C:/docker-db-volume:/var/lib/postgresql/data"

#  pgadmin
#  container_name: pgadmin4_container
#  image: dpage/pgadmin4:7
#  restart: always
#  environment:
#    PGADMIN_DEFAULT_EMAIL: admin@admin.com
#    PGADMIN_DEFAULT_PASSWORD: root
#  ports:
#    - "5050:80"
#  volumes:
#    - pgadmin-data:/var/lib/pgadmin
#
#volumes:
#  db-data:
#  pgadmin-data: